#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# creates a symbolic link (-s option) between the Nginx configuration file
# and the enabled sites directory 
# restart nginx
service nginx start
#terminates the first nginx process ID
kill "$(pdrep 'nginx' | head -1)"
